---
title: Blessing
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: s@blessing.works
description: 'Blessing works.

'
author: Blessing
keyword: Blessing
baseurl: ''
url: ''
github_username: blessing
markdown: kramdown
gems:
- jekyll-feed
exclude:
- agency-jekyll-theme.gemspec
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- screenshot.png
